/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NIL = 5;
  /** RegularExpression Id. */
  int CONS = 6;
  /** RegularExpression Id. */
  int LCONS = 7;
  /** RegularExpression Id. */
  int MATCH = 8;
  /** RegularExpression Id. */
  int BAR = 9;
  /** RegularExpression Id. */
  int MARROW = 10;
  /** RegularExpression Id. */
  int LET = 11;
  /** RegularExpression Id. */
  int TRUE = 12;
  /** RegularExpression Id. */
  int FALSE = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int MINUS = 15;
  /** RegularExpression Id. */
  int STAR = 16;
  /** RegularExpression Id. */
  int DIV = 17;
  /** RegularExpression Id. */
  int LPAR = 18;
  /** RegularExpression Id. */
  int RPAR = 19;
  /** RegularExpression Id. */
  int LBRA = 20;
  /** RegularExpression Id. */
  int RBRA = 21;
  /** RegularExpression Id. */
  int EQUAL = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int SEMIC = 24;
  /** RegularExpression Id. */
  int TERM = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int EQ = 29;
  /** RegularExpression Id. */
  int GT = 30;
  /** RegularExpression Id. */
  int LT = 31;
  /** RegularExpression Id. */
  int GTEQ = 32;
  /** RegularExpression Id. */
  int LTEQ = 33;
  /** RegularExpression Id. */
  int DIF = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int ASSIGN = 36;
  /** RegularExpression Id. */
  int BOX = 37;
  /** RegularExpression Id. */
  int IF = 38;
  /** RegularExpression Id. */
  int ELSE = 39;
  /** RegularExpression Id. */
  int WHILE = 40;
  /** RegularExpression Id. */
  int PRINT = 41;
  /** RegularExpression Id. */
  int PRINTLN = 42;
  /** RegularExpression Id. */
  int FN = 43;
  /** RegularExpression Id. */
  int ARROW = 44;
  /** RegularExpression Id. */
  int String = 45;
  /** RegularExpression Id. */
  int Id = 46;
  /** RegularExpression Id. */
  int Num = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"nil\"",
    "\"::\"",
    "\":?\"",
    "\"match\"",
    "\"|\"",
    "\"->\"",
    "\"let\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\":\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"~=\"",
    "\"~\"",
    "\":=\"",
    "\"box\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"=>\"",
    "<String>",
    "<Id>",
    "<Num>",
  };

}
