/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 8;
  /** RegularExpression Id. */
  int TYPE = 9;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int PIPE = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int STAR = 15;
  /** RegularExpression Id. */
  int DIV = 16;
  /** RegularExpression Id. */
  int LPAR = 17;
  /** RegularExpression Id. */
  int RPAR = 18;
  /** RegularExpression Id. */
  int LBRA = 19;
  /** RegularExpression Id. */
  int RBRA = 20;
  /** RegularExpression Id. */
  int EQUAL = 21;
  /** RegularExpression Id. */
  int DOT = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int DCOLON = 24;
  /** RegularExpression Id. */
  int LCOLON = 25;
  /** RegularExpression Id. */
  int SEMIC = 26;
  /** RegularExpression Id. */
  int TERM = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int EQ = 31;
  /** RegularExpression Id. */
  int GT = 32;
  /** RegularExpression Id. */
  int LT = 33;
  /** RegularExpression Id. */
  int GE = 34;
  /** RegularExpression Id. */
  int LE = 35;
  /** RegularExpression Id. */
  int NEQ = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int ASSIGN = 38;
  /** RegularExpression Id. */
  int BOX = 39;
  /** RegularExpression Id. */
  int NIL = 40;
  /** RegularExpression Id. */
  int DEREF = 41;
  /** RegularExpression Id. */
  int IF = 42;
  /** RegularExpression Id. */
  int ELSE = 43;
  /** RegularExpression Id. */
  int WHILE = 44;
  /** RegularExpression Id. */
  int PRINT = 45;
  /** RegularExpression Id. */
  int PRINTLN = 46;
  /** RegularExpression Id. */
  int FN = 47;
  /** RegularExpression Id. */
  int ARROW = 48;
  /** RegularExpression Id. */
  int SARROW = 49;
  /** RegularExpression Id. */
  int MATCH = 50;
  /** RegularExpression Id. */
  int INT = 51;
  /** RegularExpression Id. */
  int UNIT = 52;
  /** RegularExpression Id. */
  int BOOL = 53;
  /** RegularExpression Id. */
  int STRING = 54;
  /** RegularExpression Id. */
  int LIST = 55;
  /** RegularExpression Id. */
  int REF = 56;
  /** RegularExpression Id. */
  int UNION = 57;
  /** RegularExpression Id. */
  int STRUCT = 58;
  /** RegularExpression Id. */
  int Label = 59;
  /** RegularExpression Id. */
  int String = 60;
  /** RegularExpression Id. */
  int Id = 61;
  /** RegularExpression Id. */
  int Num = 62;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "<token of kind 6>",
    "\"*/\"",
    "\"let\"",
    "\"type\"",
    "\"true\"",
    "\"false\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\".\"",
    "\":\"",
    "\"::\"",
    "\":?\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"~\"",
    "\":=\"",
    "\"box\"",
    "\"nil\"",
    "\"!\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"=>\"",
    "\"->\"",
    "\"match\"",
    "\"int\"",
    "\"()\"",
    "\"bool\"",
    "\"string\"",
    "\"list\"",
    "\"ref\"",
    "\"union\"",
    "\"struct\"",
    "<Label>",
    "<String>",
    "<Id>",
    "<Num>",
  };

}
